// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package retailer

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type LoginResult interface {
	IsLoginResult()
}

type Diamond struct {
	ID           string `json:"id"`
	Color        string `json:"color"`
	Clarity      string `json:"clarity"`
	Measurements string `json:"measurements"`
}

type LoginData struct {
	User           *User        `json:"user"`
	CompanyCreated bool         `json:"companyCreated"`
	CompanyType    *CompanyType `json:"companyType,omitempty"`
}

type LoginError struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

func (LoginError) IsLoginResult() {}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginSuccess struct {
	Success bool       `json:"success"`
	Message string     `json:"message"`
	Data    *LoginData `json:"data"`
}

func (LoginSuccess) IsLoginResult() {}

type Mutation struct {
}

type Query struct {
}

type RegisterError struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type RegisterInput struct {
	FirstName string  `json:"firstName"`
	LastName  *string `json:"lastName,omitempty"`
	Email     string  `json:"email"`
	Phone     string  `json:"phone"`
	Password  string  `json:"password"`
}

type User struct {
	ID              string  `json:"id"`
	FirstName       *string `json:"firstName,omitempty"`
	LastName        *string `json:"lastName,omitempty"`
	Email           string  `json:"email"`
	Phone           string  `json:"phone"`
	IsEmailVerified bool    `json:"isEmailVerified"`
	IsPhoneVerified bool    `json:"isPhoneVerified"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
}

type UserResponse struct {
	ID              *string `json:"id,omitempty"`
	Email           *string `json:"email,omitempty"`
	Phone           *string `json:"phone,omitempty"`
	IsEmailVerified bool    `json:"isEmailVerified"`
	IsPhoneVerified bool    `json:"isPhoneVerified"`
	CreatedAt       string  `json:"createdAt"`
	UpdatedAt       string  `json:"updatedAt"`
}

type CompanyType string

const (
	CompanyTypeMerchant CompanyType = "MERCHANT"
	CompanyTypeRetailer CompanyType = "RETAILER"
)

var AllCompanyType = []CompanyType{
	CompanyTypeMerchant,
	CompanyTypeRetailer,
}

func (e CompanyType) IsValid() bool {
	switch e {
	case CompanyTypeMerchant, CompanyTypeRetailer:
		return true
	}
	return false
}

func (e CompanyType) String() string {
	return string(e)
}

func (e *CompanyType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompanyType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompanyType", str)
	}
	return nil
}

func (e CompanyType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompanyType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompanyType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserType string

const (
	UserTypeMerchant UserType = "MERCHANT"
	UserTypeRetailer UserType = "RETAILER"
)

var AllUserType = []UserType{
	UserTypeMerchant,
	UserTypeRetailer,
}

func (e UserType) IsValid() bool {
	switch e {
	case UserTypeMerchant, UserTypeRetailer:
		return true
	}
	return false
}

func (e UserType) String() string {
	return string(e)
}

func (e *UserType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserType", str)
	}
	return nil
}

func (e UserType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
