// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package merchant

type Diamond struct {
	ID      string `json:"id"`
	Color   string `json:"color"`
	Clarity string `json:"clarity"`
}

type Query struct {
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}
