package merchant

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"suregem/src/schemas/merchant"
)

// Diamond is the resolver for the diamond field.
func (r *queryResolver) Diamond(ctx context.Context, id string) (*merchant.Diamond, error) {
	panic(fmt.Errorf("not implemented: Diamond - diamond"))
}

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) GetDiamonds(ctx context.Context) ([]*merchant.Diamond, error) {
	var data = []*merchant.Diamond{
		{
			ID:      "12sw2",
			Color:   "white",
			Clarity: "tich",
		},
	}
	return data, nil
	// panic(fmt.Errorf("not implemented: GetDiamonds - getDiamonds"))
}
func (r *queryResolver) GetTodo(ctx context.Context) ([]*merchant.Todo, error) {

	var data = []*merchant.Todo{
		{
			Text:   "12sw2",
			Status: "white",
		},
	}
	return data, nil
	// panic(fmt.Errorf("not implemented: GetTodo - getTodo"))
}
*/
