package retailer

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"suregem/src/schemas/retailer"
)

// Diamond is the resolver for the diamond field.
func (r *queryResolver) Diamond(ctx context.Context, id string) (*retailer.Diamond, error) {
	panic(fmt.Errorf("not implemented: Diamond - diamond"))
}
