package retailer

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"suregem/src/middleware"
	"suregem/src/schemas/retailer"
	"suregem/src/utils"
)

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input retailer.LoginInput) (retailer.LoginResult, error) {

	// 1:  call authService
	body, httpResponse, err := r.authService.Login(ctx, input)
	if err != nil {
		return &retailer.LoginError{
			Message: err.Error(),
			Success: false,
		}, nil
	}

	// 2: forward cookies + headers to client
	utils.ForwardBackendResponse(ctx, httpResponse)

	//4: map response
	fmt.Println("body", body)

	return nil, nil

}

// Logout is the resolver for the Logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*retailer.LogoutSuccess, error) {
	appCtx := middleware.GetAppContext(ctx)
	if appCtx == nil {
		return &retailer.LogoutSuccess{
			Success: false,
			Message: "Context missing",
		}, nil
	}

	// clear cookies
	utils.ClearCookie(appCtx.Writer, "dat")
	utils.ClearCookie(appCtx.Writer, "drt")

	return &retailer.LogoutSuccess{
		Success: true,
		Message: "Logged out successfully",
	}, nil
}
