package retailer

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"fmt"
	"log"
	"suregem/src/schemas/retailer"
)

// Register is the resolver for the Register field.
func (r *mutationResolver) Register(ctx context.Context, input retailer.RegisterInput) (*retailer.User, error) {
	fmt.Print(input)
	panic(fmt.Errorf("not implemented: Register - Register"))
}

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input retailer.LoginInput) (*retailer.LoginResponse, error) {

	fmt.Print("called login grph")
	var apiResp map[string]interface{}
	err := r.client.Post("/user/login", map[string]string{
		"email":    input.Email,
		"password": input.Password,
	}, &apiResp)

	if err != nil {
		log.Println("login failed:", err)
		return nil, err
	}

	log.Println("login response:", apiResp)
	return nil, nil

	// firstName := "John"
	// companyType := retailer.CompanyType("RETAILER")

	// return &retailer.LoginResponse{
	// 	User: &retailer.User{
	// 		ID:              "123",
	// 		FirstName:       &firstName,
	// 		Email:           "john@gmail.com",
	// 		Phone:           "+1234567890",
	// 		IsEmailVerified: true,
	// 		IsPhoneVerified: false,
	// 		CreatedAt:       "2024-01-15T10:30:00Z",
	// 		UpdatedAt:       "2024-01-15T10:30:00Z",
	// 	},
	// 	CompanyCreated: true,
	// 	CompanyType:    &companyType,
	// }, nil
}
