package retailer

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"
	"suregem/src/middleware"
	"suregem/src/schemas/retailer"
	"suregem/src/utils"
)

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input retailer.LoginInput) (retailer.LoginResult, error) {

	return nil, nil
}

// Logout is the resolver for the Logout field.
func (r *mutationResolver) Logout(ctx context.Context) (*retailer.LogoutSuccess, error) {
	appCtx := middleware.GetAppContext(ctx)
	if appCtx == nil {
		return &retailer.LogoutSuccess{
			Success: false,
			Message: "Context missing",
		}, nil
	}

	// clear cookies
	utils.ClearCookie(appCtx.Writer, "dat")
	utils.ClearCookie(appCtx.Writer, "drt")

	return &retailer.LogoutSuccess{
		Success: true,
		Message: "Logged out successfully",
	}, nil
}
